Hello Microverse pull request
firstpj/hello-microverse pull request #1
Opened 2023-02-18 02:19 UTC by firstpj

2023-02-21 08:12 UTC, Ibizugbe requested changes
Hi @firstpj 👋👋, 

![tryagain](https://user-images.githubusercontent.com/64643995/220284708-c9e85f22-b5ae-432a-9d7c-3fc4b7806795.gif)


Good job so far!👍
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights✅✅

- [ ] Linters are passing👍
- [ ] Pull request is made from a `feature` branch to the `main` branch👍
- [ ] `HTML` and `CSS` files have been added with the  required contents👍


## Required Changes ♻️

- [ ] I can see you have put in some effort in documenting your project with your readme👍 But lets make it more professional😉 Kindly make use of the microverse [readme template](https://github.com/microverseinc/readme-template) and follow the instructions on how to use the template, given in the [template](https://github.com/microverseinc/readme-template)😎😎 don't forget we are [required](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/documentation/hello_microverse_project.md) to use the template to document our project in this milestone😉
<img width="666" alt="readme hello" src="https://user-images.githubusercontent.com/64643995/220285955-396f5edb-7241-47cd-90ec-68a8d9e1ba64.png">


_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-21 13:19 UTC, osamaashraf6 requested changes
Hi  @firstpj ☺️, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't been addressed yet.

![you-are-near](https://media.giphy.com/media/SSR17K6yZWvGCYrfUh/giphy.gif)

## Highlights ✔️

- [x] No linter errors. 💯
- [x] Good Setup configuration files and folders
- [x]  Correct Github-flow

 ## Required Changes ♻️

- As stated by the 😊previous reviewer Kindly use [the Microverse Readme template](https://github.com/microverseinc/readme-template) and make sure all the main sections present in yours and placeholders are replaced with your project and personal data. The only optional section is a FAQ. Please remove the template logo on the top, if you have one, you can replace it. This is crucial to have a professional and instructive repository. 👌
😃

## Optional suggestions
- N/A

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-21 16:53 UTC, mckent05 approved these changes
Hi @firstpj, 

# STATUS: APPROVED ✔️ ✔️ 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations and well done! 🎉 
![approved](https://user-images.githubusercontent.com/73607512/207264357-1b05ce6a-95f2-4d31-9c26-888c6ddfa124.gif)


## Highlights
- All linter checks are passing ✔️ ✔️ 
- Your PR is professional 👏 👏 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-21 12:34 UTC, binhussen requested changes
Hi @firstpj , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
<img src="https://media0.giphy.com/media/UdaSUYClr92cjWpeVx/giphy.gif"/>

## Highlights

- All linter checks passed ✔️
- Descriptive pull request ✔️
- Used GitHub flow ✔️

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-21 12:34 UTC, binhussen commented on README.md
> +- [Live Demo Link](N/A)
- Kindly, your live demo link is broken, please correct the link or remove it and replace it with text such as `coming soon`, because a broken link will lead to bad user experience 👍

2023-03-22 08:53 UTC, didierganthier requested changes
Hi @firstpj ,

🎉 Great job on addressing the feedback from the previous review! You've made some solid progress in implementing the requested changes. However, there are still a few areas that need some attention before we can move on to the next project.

<img src="https://media.giphy.com/media/e56n4Z0mmkxZS/giphy.gif" />

## Highlights
- Descriptive PR ✔️ 
- Added `.gitginore` ✔️ 
- Correct GitHub flow ✔️ 

## Required Changes 🛠
- [ ] Nice work 👍🏽 but there seem to be some conflicts between your branches and they're causing your linters checks to not run 👇🏽 
![Screenshot 2023-03-22 at 04 44 23](https://user-images.githubusercontent.com/45739963/226849422-3cfd1c48-90f8-4ae5-a852-da59a29fb477.png)

Look to solve these conflicts ❌ and request another review 🤓 

- Please review the comments under the review for specific changes that still need to be made.

## Optional Suggestions 💡
- While these comments with the [OPTIONAL] prefix won't prevent the approval of this pull request, I strongly recommend taking them into account as they can improve your code. Some of them were missed by the previous reviewer and addressing them will really enhance your application.

🚀 Keep pushing forward, you're almost there! If you have any questions or need clarification on anything, feel free to leave a comment in the pull request thread and don't forget to tag me so I'll receive the notification.

**Please note**
- To avoid confusion and delays, please do not open a new pull request for re-reviews. Use the same pull request submitted for the first review, unless otherwise instructed.

------
As per the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561), you have a limited number of reviews per project. If you feel that the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s). 

Cheers and happy coding! 👏👏👏

2023-03-22 08:53 UTC, didierganthier commented on README.md
> +
Well done on the README 💯 but you made a formatting error here by forgetting to add ``` in line `111` to encapsulate the code like that :
```sh
  cd my-folder
  git clone git@github.com:firstpj/hello-microverse.git
```
The bad formatting makes your README look like this 👇🏽 

![Screenshot 2023-03-22 at 04 47 40](https://user-images.githubusercontent.com/45739963/226848878-87815ca3-6fdf-4ea5-90f6-7d446827b751.png)

2023-03-23 09:50 UTC, AbelG101 approved these changes
![](https://media.giphy.com/media/xT0BKhunZXlEsnpz7q/giphy.gif)

## Hi @firstpj  👋, 

Your project is complete!  There is nothing else to say other than... it's time to merge it. 
Congratulations! 🎉 

## Highlights
- Correct use of GitHub Flow ✔
-  Well-structured files ✔
- All linter checks are passing ✔
- Descriptive PR title✔

## Optional suggestions
- N/A
_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-05 07:11 UTC, merged